services:
  - type: web
    name: ippolito.dev
    env: node
    branch: main
    startCommand: node .output/server/index.mjs
    buildCommand: npm install && npm run build
    envVars:
    - key: NITRO_PRESET
      value: render_com